apiVersion: v1
kind: Service
metadata:
  name: go-httpbin
  labels:
    app: go-httpbin
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31200
  type: NodePort
  selector:
    app: go-httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-httpbin
  labels:
    app: go-httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-httpbin
  template:
    metadata:
      labels:
        app: go-httpbin
    spec:
      containers:
      - name: go-httpbin
        image: xcbeyond/go-httpbin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080